bam: /scratch/mkiyer_root/mkiyer0/shared_data/hulkrna/runs/human/ccle_capan_1_pancreas/rigel/collate.bam
index: /scratch/mkiyer_root/mkiyer0/shared_data/hulkrna/refs/human/rigel_index

outdir: results/profile_vbem_large

rigel_configs:
  vbem_8t:
    em_mode: vbem
    n_threads: 8
